// Copyright (C) 2024 wwhai
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
package yolo8

var CoCo8ClassesEN = map[int]string{
	0:  "person",
	1:  "bicycle",
	2:  "car",
	3:  "motorcycle",
	4:  "airplane",
	5:  "bus",
	6:  "train",
	7:  "truck",
	8:  "boat",
	9:  "traffic light",
	10: "fire hydrant",
	11: "stop sign",
	12: "parking meter",
	13: "bench",
	14: "bird",
	15: "cat",
	16: "dog",
	17: "horse",
	18: "sheep",
	19: "cow",
	20: "elephant",
	21: "bear",
	22: "zebra",
	23: "giraffe",
	24: "backpack",
	25: "umbrella",
	26: "handbag",
	27: "tie",
	28: "suitcase",
	29: "frisbee",
	30: "skis",
	31: "snowboard",
	32: "sports ball",
	33: "kite",
	34: "baseball bat",
	35: "baseball glove",
	36: "skateboard",
	37: "surfboard",
	38: "tennis racket",
	39: "bottle",
	40: "wine glass",
	41: "cup",
	42: "fork",
	43: "knife",
	44: "spoon",
	45: "bowl",
	46: "banana",
	47: "apple",
	48: "sandwich",
	49: "orange",
	50: "broccoli",
	51: "carrot",
	52: "hot dog",
	53: "pizza",
	54: "donut",
	55: "cake",
	56: "chair",
	57: "couch",
	58: "potted plant",
	59: "bed",
	60: "dining table",
	61: "toilet",
	62: "tv",
	63: "laptop",
	64: "mouse",
	65: "remote",
	66: "keyboard",
	67: "cell phone",
	68: "microwave",
	69: "oven",
	70: "toaster",
	71: "sink",
	72: "refrigerator",
	73: "book",
	74: "clock",
	75: "vase",
	76: "scissors",
	77: "teddy bear",
	78: "hair drier",
	79: "toothbrush",
}
