// Copyright (C) 2024 wwhai
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
package yolo8

var CoCo8ClassesCN = map[int]string{
	0:  "人",
	1:  "自行车",
	2:  "汽车",
	3:  "摩托车",
	4:  "飞机",
	5:  "公共汽车",
	6:  "火车",
	7:  "卡车",
	8:  "船",
	9:  "交通灯",
	10: "消防栓",
	11: "停止标志",
	12: "停车计时器",
	13: "长凳",
	14: "鸟",
	15: "猫",
	16: "狗",
	17: "马",
	18: "羊",
	19: "牛",
	20: "大象",
	21: "熊",
	22: "斑马",
	23: "长颈鹿",
	24: "背包",
	25: "雨伞",
	26: "手提包",
	27: "领带",
	28: "手提箱",
	29: "飞盘",
	30: "滑雪板",
	31: "滑雪板",
	32: "运动球",
	33: "风筝",
	34: "棒球棒",
	35: "棒球手套",
	36: "滑板",
	37: "冲浪板",
	38: "网球拍",
	39: "瓶子",
	40: "酒杯",
	41: "杯子",
	42: "叉子",
	43: "刀",
	44: "勺子",
	45: "碗",
	46: "香蕉",
	47: "苹果",
	48: "三明治",
	49: "橙子",
	50: "西兰花",
	51: "胡萝卜",
	52: "热狗",
	53: "披萨",
	54: "甜甜圈",
	55: "蛋糕",
	56: "椅子",
	57: "沙发",
	58: "盆栽植物",
	59: "床",
	60: "餐桌",
	61: "厕所",
	62: "电视",
	63: "笔记本电脑",
	64: "鼠标",
	65: "遥控器",
	66: "键盘",
	67: "手机",
	68: "微波炉",
	69: "烤箱",
	70: "烤面包机",
	71: "水槽",
	72: "冰箱",
	73: "书",
	74: "时钟",
	75: "花瓶",
	76: "剪刀",
	77: "泰迪熊",
	78: "吹风机",
	79: "牙刷",
}
